### ISSUE TITLE
Add one additional sequence format - fasta_MolD

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/DNAconvert#29]
Our suite of tools includes one program, MolD, that is doing similar things as dnadiagnoser but requires a specific input format. Since this format is rather easy to specify, it would be great if it could be added to the formats of dnaconvert, so that it becomes easy to prepare MolD input files.

The MolD input file is a simple fasta file, but the sequence name needs to be prepared in a specific way, like in these examples:

>alisi1|alisi
>ZCMV1234|Mantella_aurantiaca
>ZSM20080176|verrucosa

So, basically, there is a sequence or specimen identifier as first part of the sequence name, then a pipe symbol | followed by the species name. Neither of the two parts of the sequence name should contain any special characters or spaces.

For composing the name when converting tab -> fasta_MolD, follow the following rules:

1. For the first part of the name, if in the tabfile there is a field "specimen_voucher" or "isolate" (in this order of priority) then use the content of this field for the first part, and for those rows where there is no value for this field, use a consecutively numbered replacement: sequence1, sequence2, sequence3.....
If there is no field "specimen_voucher" or "isolate", then use the rules for regular (not relaxed) Phylip format.
Make sure to use the usual replacement to make sure no special characters, spaces etc. make it into the sequence name.

2. For the second part of the name, use the content of the column/field "species" or "organism" (in this order of priority) and if there is no value, just add nothing after the "pipe" character.

When converting fasta_MolD to other tab, separate the name, so that the first part of the name goes into the column "seqid" and the second part of the name (after the pipe character) goes into a column "species". The pipe character is removed. 

When transforming fasta_MolD to other formats, just follow the same rules as for fasta. The pipe character will be replaced by an underscore.

**Comment by necrosovereign** [comment]
Does using the rules for regular Phylip format means that the first part of the name should be no longer than 10 characters and be unique?

**Comment by mvences** [comment]
Yes, exactly, this is what I meant.

**Comment by necrosovereign** [comment]
And what if the 'specimen_voucher' is longer than 10 characters, like 'ZSM20080176' in the example?

**Comment by mvences** [comment]
This is no problem, there is not really a length restriction in MolD, so if we have a specimen voucher of 10 or 20 or 30 characters, it is no problem. 
The problem with  the "seqid" field is that sometimes it can have VERY LONG content of even several 100 characters, for instance when converting from GB, and then it would look very clumsy to have this in the MolD_fasta format. That's why for this case I would prefer a rule to shorten it to 10 characters. But specimen-voucher content will never be excessively long, so it is not problem to leave it free.
