### ISSUE TITLE
Add extension tsv = tab

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/DNAconvert#35]
When first coming up with the description of the various tools, including DNAdiagnoser, I suggested naming tab-delimited text files with the extension ".tab" but only recently I realized that an already existing extension for this formatwould be ".tsv". So we should enable to program to understand tsv=tab
- For input files named .tsv without specification of format, the program should automatically assume this is the tab-delimited format
- For tab-delimited output files, we need to consider whether we want to have these as default with the extension ".tab" or with the more widely used ".tsv". To be discussed and decided when we start working on a new version of the program.

**Comment by necrosovereign** [comment]
The program already recognizes ".tsv" extension as tabfile. For the output file the extension is specified by the user.
