### ISSUE TITLE
Slight modification to "fasta_gbexport" format

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/DNAconvert#42]
I have been using DNAconvert a lot to prepare sequences for Genbank export. One thing that was always weird was the modified seqid. The program modifies seqid by adding a running number at the end, which is good to make sure all seqids are different from each other. These seqids are only used as a temporary ID during the submission process, so it is not really a problem, but ... when Genbank send back the accession numbers, it refers back to these seqids, like the following:

-----------------

Dear GenBank Submitter:

We have provided GenBank accession number(s) for your nucleotide sequence(s):

SUB11572552 FGZC_62070    	ON710980
SUB11572552 FGZC_62531    	ON710981
SUB11572552 FGZC_62542    	ON710982
SUB11572552 FGZC_62813    	ON710983
SUB11572552 FGZC_63344    	ON710984
SUB11572552 ZSM_1980_20085	ON710985
SUB11572552 ZSM_1985_20086	ON710986
SUB11572552 ZSM_1986_20087	ON710987
SUB11572552 FGZC_33008    	ON710988
SUB11572552 FGZC_53429    	ON710989

---------------------

Since I am typically using the specimen-voucher numbers as seqid, the added number is often confusing when trying to find out readily which of the new accession number refers to which sequence.

Please modify the output format so that as an additional character also an underscore is added at the end: 

If the seqid of the first sequence is FGZC1234
it is now transformed to FGZC12341
and after the change it should instead be transformed to FGZC1234_1
This will make it easier to understand that the additional number has just been added by the program.

This is a low priority issue and can be addressed whenever there are a few minutes of time for it.

**Comment by necrosovereign** [comment]
The easiest way to do this change this will also apply it to the Nexus, Phylip, Hapview Fasta and Mold Fasta.

**Comment by mvences** [comment]
Yes, this is fine. It will indeed be better to have the same modification for all cases and all formats where this numbering process takes place.
