### ISSUE TITLE
Improve support for MolD fasta and add support for ali files

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/DNAconvert#46]
Improve support for MolD-fasta --- when converting into tab the species name will be printed into a separate column "species", and when converting from tab (if not yet implemented) content of species/organism field will be appended after a pipe symbol.

Add support for ali files --- a few special modifications of standard fasta should be added when converting to ali , such as the initial line with a hashtag symbol etc.

**Comment by necrosovereign** [comment]
It would be useful to have sample input files with expected output files.

**Comment by mvences** [comment]
Here are two MolD example files in a ZIP folder. The specifications describe the format as follows:

Fasta file in the format required by MolD: each entry starts with the identifier line, and one or more lines of nucleotide sequence. Identifier line starts with ‘>’ and must contain two parts, separated by a pipe (‘|’) symbol. The first part is a free-style sequence identifier. The names of the taxa to be diagnosed correspond to the second element, i.e., the taxon identifier: >SequenceID####|taxon. The taxon identifier corresponds to the name of the species, genus etc to which you assign this sequence. 
The "taxon" identifier should not contain special characters such as spaces, dashes and so on, therefore when converting from tab/tsv format to MolD fasta, the content of "organism" or "species" should be sanitized by replacing all special characters by underscores.
We would expect that only one of the two, species or organism, are present in the tab file. If both are present, either issue an error message or give "species" precedence over "organism (whatever is easier to implement).



[MolD_examplefiles_iTaxoTools_0_1.zip](https://github.com/iTaxoTools/DNAconvert/files/10579344/MolD_examplefiles_iTaxoTools_0_1.zip)

**Comment by mvences** [comment]
Here is a ZIP folder with two ali format files. These are with protein not DNA sequences but they should suffice to illustrate the general format.
- When converting any other format into ali, the two empty lines with hashtag at the beginning need to be added, everything else is identical to fasta.
- When converting into other formats such ali files that have sequences preceded by spaces (like in example 1), then these spaces should be transformed into question marks. (later in advanced options we can allow for two options - transform into question marks, dashes or asterisks, or simply remove the spaces) 

[ali_example_files.zip](https://github.com/iTaxoTools/DNAconvert/files/10579405/ali_example_files.zip)

**Comment by necrosovereign** [comment]
If a tab file looks like this:
```
seqid          species        location       country        sequence
1234           abc            Def            Xyz            ATGTCC
```

How should this be translated into the MolD format?

Currently, the result is:
```
>abc_def_xy|abc
ATGTCC
```

**Comment by mvences** [comment]
I think this is an excellent solution, yes!

If the other columns are not there (only seqid and species) then just use the seqid:
>1234|abc

If there is no "species" column but an "organism" column, then the content of organism should be put behind the "pipe" character.

If there is species and "organism", then prioritize "species" and ignore organism.

If there is neither "species" nor "organism", then display an error message.
