### ISSUE TITLE
Fix problem with differently formatted Genbank files

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/DNAconvert#49]
Here is one quite important issue that I just remembered. One of the really nice options of DNAconvert which I am using a lot is the conversion of Genbank files. Usually this works, but with some records it fails. Especially, Genbank files from so-called DNA barcode sequences seem to be formatted in a somewhat different way. This cause the program to fail in the conversion.

Below is a ZIP file with an example file which contains several such barcodes, and at least one (probably more) of them have this wrong formatting and therefore cannot be converted. One problem seems to be that "authors" are given more than once per file.

It will be good if the conversion of Genbank files can be made more robust:

1. If possible, it should be able to convert also Genbank-formatted files that deviate from the "typical" formatting, in particular the DNA barcode files as in the example attached.

2.  In addition, it will be good if the program, when encountering an unexpected "problematic" record it cannot properly interpret, just issues a warning but goes on and tries to find the next record, and proceed with the conversion of that one (perhaps leaving especially in the conversion to tsv, one row in the column empty, only with information on seqid which should usually be found in all records, even malformed ones).

[testbarcodes.zip](https://github.com/iTaxoTools/DNAconvert/files/10724184/testbarcodes.zip)

**Comment by necrosovereign** [comment]
It seems that the problem is caused by "authors" missing in some records, such as the one with accession "HM400304".
I will add code to skip such records and add a warning.

**Comment by mvences** [comment]
[I originally added this comment to the pull request, but I am not sure if you have seen it there, so just in case I am also copying it here]


I am not merging this pull request for now since I would prefer a different solution. But I am not sure how easy if it is to implement. If it is too complicated to implement, we can stick with the current improvement.

My suggestion would be, in case of a malformed Genbank record, not skipping the entire record but trying to extract as much as possible the information and including it in the respective output file (usually a tab or Fasta file) but still issuing an error message stating that something with one or several records was malformed or missing in the input file.

Usually, at least the sequence and a seqid should be present. Of course if the program cannot find/identify these, then it should just skip the entire record.

But if for instance just the author information is missing, then including the sequence in the output file with the remaining information would be no problem. Basically this means, treating "author" as an optional information that might or might not be present (although it usually is).
