### ISSUE TITLE
Additional DNAconvert modifications after testing

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/DNAconvert#51]
The following are minor things that showed up after looking at the newly compiled DNAconvert. I think it should be relatively easy to address most of those.

1. Allow full-length seqids/specimen-voucher numbers in mold-fasta format:
In the current implementation, the program composes the sequence or sample identity part of the mold-fasta sequence names (i.e., the text string before the pipe format) by abbreviating/trimming it to a limited number of characters, similar to formats such as Phylip. 
However, the new version of MolD now allows for sample names of unlimited length, therefore this numbering should better be removed. Ideally the program should compose this part of the sequence name (before the pipe) with the following rules:
- look for a column specimen-voucher (or specimen_voucher). If present, then use the content of this column for the sequence name part before the pipe. 
- If there is no specimen-voucher column then use the content of the "seqid" column should be placed before the pipe. 
- In both cases, the name should be sanitized (all special characters replaced by underscores), but no length restriction.
- If neither specimen-voucher nor seqid is found in the file, issue a warning.

2. Add default info to format drop-down menus

Presently, the Input format and Output format drop down menus are empty as a default, and in this stage, the program will automatically infer the file format from the file extension of the files specified. But this is not made clear to the user. So, it will be good if as a default, the menu reads "Inferred from file extension" (or "Auto from file extension" or just "From file extension", if this better fits the box - but see also next point below which will require making the menu wider).

Then, it will also be good if this option ("Inferred from file extension") can be chosen by the user as one of the various options in the drop-down menu.

3. Improve description and order of formats in drop-down menu

The drop-down menu is perfectly doing its job, but for new users, it may not be immediately clear which format is which, and the order of formats is also not ideal. 
Currently, the format names are written with underscores, but I suppose this is not really necessary and standard spaces would also be accepted in the menu?

If would be good if the formats could be changed to the following new names (because the names are somewhat longer, it means in the menu the menu needs to be made wider, but I think it should still fit without having to increase the overall size of the DNAconvert window):

tab --> Tab-separated values
tab no headers --> Tab-separated values, no headers
fasta --> Fasta
relaxed phylip --> Phylip (relaxed)
phylip --> Phylip (standard)
fastq --> Fastq
fasta_gbexport --> Fasta (for export to Genbank)
nexus --> Nexus
nexml --> NeXML
genbank --> Genbank flat file
mold_fasta --> Fasta (for MolD)
ali_fasta --> Fasta ("ali" variant)

and then re-ordered as follows:

Inferred from file extension
Tab-separated values
Tab-separated values, no headers
Fasta
Fasta (for export to Genbank)
Fasta (for MolD)
Fasta ("ali" variant)
Fastq
Nexus
NeXML
Phylip (standard)
Phylip (relaxed)
Genbank flat file

**Comment by necrosovereign** [comment]
The way drop-down menus are implemented in Tk (the GUI framework used by DNAconvert) requires that the internal and displayed values are the same. Implementing 3 would require some amount of error-prone string manipulation.

**Comment by mvences** [comment]
OK, if this is the case then better leave as is, at least for now. I will close this issue for now, but we may get back to it at some later point - perhaps in the future, we can make a new DNAconvert base don the Qt GUI system and address this point.

**Comment by mvences** [comment]
ISorry for the confusion, I have reopened the issue because there is still the first point ("Allow full-length seqids/specimen-voucher numbers in mold-fasta format:") to be addressed.
